services:
  arch_zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: arch_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  arch_kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: arch_kafka
    depends_on:
      - arch_zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'arch_zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://arch_kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  aetherion_postgres:
    image: postgres:16-alpine
    container_name: aetherion_postgres
    environment:
      POSTGRES_USER: supersonic_user
      POSTGRES_PASSWORD: Mv@20217$$
      POSTGRES_DB: supersonic
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  aetherion_cassandra:
    image: cassandra:4.1
    container_name: aetherion_cassandra
    ports:
      - "9042:9042"

  aetherion_mongo:
    image: mongo:7.0
    container_name: aetherion_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"

  aetherion_couchdb:
    image: couchdb:3.3
    container_name: aetherion_couchdb
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: admin
    ports:
      - "5984:5984"

  arch_redis:
    image: redis:7-alpine
    container_name: arch_redis
    ports:
      - "6379:6379"
